### PR TITLE
Added environment file for improved project configuration management.

### LINKED ISSUE #6: Create environment.yaml file for project

### PR DESCRIPTION
**Pull request by nassimgha**
The environment file has been added based on what we need for the project. Please check and let me know if anything needs to change.

### CODE REVIEW

**Comment by iris0614** [comment]
- The commit message is too short, so please check the guidelines in the issues first.
(https://github.com/UBC-MDS/DSCI-532_2024_5_Estates_Track/issues/2)
- So you need to change the commit message.You could refer: https://stackoverflow.com/questions/179123/how-to-modify-existing-unpushed-commit-messages 
- and git push again after changing the commit message(example: Added environment file for improved project configuration management.)

**Review by iris0614 — COMMENTED** [review]
Regarding this PR, I might make some adjustments to this file, especially when attempting challenging parts. Therefore, let's keep it open for a while until I confirm that we no longer require additional packages for the challenging sections. Your patience and collaboration are much appreciated!

**Comment by nassimgha** [comment]
This environment file includes all the packages listed on the course 532. So, it should be fine.

**Review by iris0614 — APPROVED** [review]
for milestone1 is good enough

**Pull request merged**
