### PR TITLE
Creating folder structure for our project

### LINKED ISSUE #3: Create project folder structure

### PR DESCRIPTION
**Pull request by Aishwarya120111**

### CODE REVIEW

**Review by iris0614 — APPROVED** [review]
looks good!

**Review by nassimgha — CHANGES_REQUESTED** [review]
Thank you for the folder structure. I was looking at the milestone1, and noticed we also need to have a folder for data/raw, and a folder for image, which is img/sketch.png. But I could not find them here.
README.md (the project title and a summary of its purpose in ~3-4 sentences)
LICENSE.md (include the license for both software and non-software content)
CODE_OF_CONDUCT.md (include a citation if you used a template from elsewhere)
CONTRIBUTING.md (include a citation if you used a template from elsewhere)
src/app.py or src/app.R (this file can be empty for now, but indicates which language you are planning to use)
data/raw/ (should inlucde your chosen raw data file(s); indicate in the proposal if you plan to load from an external source instead)
notebooks/ (optional: if you start doing EDA, include your notebooks in this folder)
environment.yml (can contain just the basics for now, e.g. the libraries for the dashboard, data wrangling, and vizualization; include version numbers)
reports/m1_proposal.md (see below)
img/sketch.png (see below)

**Comment by Aishwarya120111** [comment]
> Thank you for the folder structure. I was looking at the milestone1, and noticed we also need to have a folder for data/raw, and a folder for image, which is img/sketch.png. But I could not find them here. README.md (the project title and a summary of its purpose in ~3-4 sentences) LICENSE.md (include the license for both software and non-software content) CODE_OF_CONDUCT.md (include a citation if you used a template from elsewhere) CONTRIBUTING.md (include a citation if you used a template from elsewhere) src/app.py or src/app.R (this file can be empty for now, but indicates which language you are planning to use) data/raw/ (should inlucde your chosen raw data file(s); indicate in the proposal if you plan to load from an external source instead) notebooks/ (optional: if you start doing EDA, include your notebooks in this folder) environment.yml (can contain just the basics for now, e.g. the libraries for the dashboard, data wrangling, and vizualization; include version numbers) reports/m1_proposal.md (see below) img/sketch.png (see below)

@nassimgha thank you for checking on this. I have added it now. Could you please check it now.

**Review by nassimgha — APPROVED** [review]
Thank you, looks great!

**Pull request merged**
